create schema TEST;

create table SYS_USER(
  ID BIGINT,
  USER_NAME VARCHAR(100),
  PASSWORD VARCHAR(100),
  CONSTRAINT USER_PK PRIMARY KEY (ID)
);

create TABLE SYS_ROLE(
  ID BIGINT,
  NAME VARCHAR(100),
  CONSTRAINT ROLE_PK PRIMARY KEY (ID)
);

create TABLE SYS_USER_ROLES(
  SYS_USER_ID BIGINT,
  ROLES_ID BIGINT
)